api/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductModelViewSet)
router.register(r'baskets', views.BasketModelViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),

]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create', views.OrderCreateView.as_view(), name='order-create'),
    path('', views.OrderListView.as_view(), name='orders-list'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('order-success', views.SuccessTemplateView.as_view(), name='order-success'),
    path('order-cancel', views.CancelTemplateView.as_view(), name='order-cancel'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', views.ProductsListView.as_view(), name='category'),

    path('basket/add/<int:product_id>/', views.basket_add, name='basket-add'),
    path('basket/remove/<int:basket_id>/', views.basket_remove, name='basket-remove'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe-webhook'),

    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', views.UserEmailVerificationView.as_view(), name='email_verification'),
]

products/models.py
import stripe
from django.conf import settings
from django.db import models

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=12, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', null=True, blank=True)
    stripe_product_price_id = models.CharField(max_length=256, null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f"Товар: {self.name} | Категория: {self.category.name}"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency='rub'
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины товаров'

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_item

    @classmethod
    def create_or_update(cls, product_id, user):
        baskets = Basket.objects.filter(user=user, product_id=product_id)

        if not baskets.exists():
            obj = Basket.objects.create(user=user, product_id=product_id, quantity=1)
            is_created = True
            return obj, is_created
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()
            is_created = False
            return basket, is_created

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from common.views import TitleMixin

from .models import Basket, Product, ProductCategory


class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'Store'


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = 3
    title = 'Store - Каталог'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all()
        context['category_id'] = self.kwargs.get('category_id')
        return context


@login_required
def basket_add(request, product_id):
    Basket.create_or_update(product_id=product_id, user=request.user)
    return redirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return redirect(request.META['HTTP_REFERER'])

products/templates/products/inc/_baskets.html
{% load humanize %}


<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
    Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
</h4>
{% if baskets %}
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ basket.product.name }}</h5>
                <p class="card-text">{{ basket.product.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                   value="{{ basket.quantity }}" min="0">
                        </div>
                        <div class="col-lg-4">{{ basket.sum|intcomma }} руб.</div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket-remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum|intcomma }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order-create' %}">
        Оформить заказ
    </a>
{% else %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title text-center">Корзина пуста</h5>
        </div>
    </div>
{% endif %}

products/templates/products/inc/_footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2023</p>
    </div>
</footer>

products/templates/products/inc/_header.html
<div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Store</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">
                        Войти <i class="fas fa-sign-in-alt"></i>
                    </a>
                </li>
            {% else %}
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-user-circle"></i>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li>
                        <a class="dropdown-item" href="{% url 'users:profile' user.id %}">
                            Профиль
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'orders:orders-list' %}">
                            Заказы
                        </a>
                    </li>
                    {% if user.is_superuser or user.is_staff %}
                        <li>
                            <a class="dropdown-item" href="{% url 'admin:index' %}">
                                Админ-панель
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">
                            Выйти
                        </a>
                    </li>
                </ul>
            {% endif %}
            </li>
        </ul>
    </div>
</div>

products/templates/products/inc/_pagination.html
{% if is_paginated %}
    <ul class="pagination justify-content-center">
        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            <a class="page-link" href="{% if page_obj.has_previous %}
                                                  ?page={{ page_obj.previous_page_number }}
                                        {% else %}
                                            #
                                        {% endif %}"
               tabindex="-1" aria-disabled="true">
                Предыдущая
            </a>
        </li>

        {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == page %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link " href="#">
                        {{ page }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            {% elif page > page_obj.number|add:-3 and page < page_obj.number|add:3 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page }}">
                        {{ page }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
            <a class="page-link" href="{% if page_obj.has_next %}
                                              ?page={{ page_obj.next_page_number }}
                                        {% else %}
                                            #
                                        {% endif %}">
                Следующая
            </a>
        </li>
    </ul>
{% endif %}

products/templates/products/inc/_sidebar.html
{#<h1 class="my-4">Store</h1>#}
<h1 class="mb-0 mt-4">
    <a href="{% url 'products:index' %}" class="btn btn-primary bg-dark btn-block ">Категории</a>
</h1>
<div class="list-group">
    {% for category in categories %}
        <a href="{% url 'products:category' category.id %}" class="list-group-item list-group-item-action">
            {{ category.name }}
        </a>
    {% endfor %}
</div>